### ISSUE TITLE
Research whether dependabot is a useful tool for us to implement

### ISSUE THREAD

**Issue by melanierogan** [wellcomecollection/platform-infrastructure#335]
We had an issue recently where we upgraded API Elastic cluster from 8.4.1 to 8.4.2 by applying the Terraform in the pipeline stack introduced a bug (from Elasticsearch). We had an incident retro and one of the points we took away was that we will try to be more explicit in the action of upgrading something. One of the suggestions we noted was around using a tool like Dependabot to tell us about what dependencies might need upgrading.  

Before we go and blanket introduce this to repos, we should discuss if Dependabot is a good option, or if there are others. Paul noted that we could just try it on and if it feels helpful, and not annoying, we keep it - that's one approach we could take if nobody has any strong opinions

**Comment by alexwlchan** [comment]
Closing as stale – we did investigate, and we tried it for a while.
