### ISSUE TITLE
Review use of productboard

### ISSUE THREAD

**Issue by kenoir** [wellcomecollection/platform-infrastructure#412]
We have a paid account with productboard, that we are considering shuttering (the account is owned by the digital engagment email address). 

https://www.productboard.com/ 

We should archive / delete our work there and close our account if we are no longer going to use it.

**Comment by LFBaily** [comment]
I believe we have agreed to remove this I'm just waiting for Jonathan to go through and remove anything relevant not already captured in the export.

**Comment by jcateswellcome** [comment]
I've added screen caps of the roadmap prioritisation here and also taken the body of all the tickets and pasted it into the export you sent me, now saved here: https://drive.google.com/drive/folders/1IGOXSi29S_wx2aWu-qD_hds5E1TsJB9o?usp=share_link

Do we want to keep all the insights on there? I am not an admin so I can't export that, but there's quite a lot of notes and votes [all of it 'historic'] but don't want to lose any of that if it is valuable? Might be some qual data of use.
